# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt/BrenoColaQt/mainwindow.ui'
#
# Created: Fri Oct 28 18:42:53 2016
#      by: PyQt5 UI code generator 5.2.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 300)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.listWidget = QtWidgets.QListWidget(self.centralWidget)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout_2.addWidget(self.listWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setContentsMargins(-1, 12, -1, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.stackRadioButton = QtWidgets.QRadioButton(self.groupBox)
        self.stackRadioButton.setObjectName("stackRadioButton")
        self.verticalLayout.addWidget(self.stackRadioButton)
        self.listRadioButton = QtWidgets.QRadioButton(self.groupBox)
        self.listRadioButton.setObjectName("listRadioButton")
        self.verticalLayout.addWidget(self.listRadioButton)
        self.concatRadioButton = QtWidgets.QRadioButton(self.groupBox)
        self.concatRadioButton.setObjectName("concatRadioButton")
        self.verticalLayout.addWidget(self.concatRadioButton)
        self.randomRadioButton = QtWidgets.QRadioButton(self.groupBox)
        self.randomRadioButton.setObjectName("randomRadioButton")
        self.verticalLayout.addWidget(self.randomRadioButton)
        self.horizontalLayout.addWidget(self.groupBox)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.centralWidget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.totalBytesValueLabel = QtWidgets.QLabel(self.centralWidget)
        self.totalBytesValueLabel.setText("")
        self.totalBytesValueLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.totalBytesValueLabel.setObjectName("totalBytesValueLabel")
        self.gridLayout.addWidget(self.totalBytesValueLabel, 2, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralWidget)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.bufferSizeValueLabel = QtWidgets.QLabel(self.centralWidget)
        self.bufferSizeValueLabel.setText("")
        self.bufferSizeValueLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.bufferSizeValueLabel.setObjectName("bufferSizeValueLabel")
        self.gridLayout.addWidget(self.bufferSizeValueLabel, 1, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralWidget)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setWordWrap(True)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_6 = QtWidgets.QLabel(self.centralWidget)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.transparencyValueLabel = QtWidgets.QLabel(self.centralWidget)
        self.transparencyValueLabel.setText("")
        self.transparencyValueLabel.setObjectName("transparencyValueLabel")
        self.horizontalLayout_2.addWidget(self.transparencyValueLabel)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.transparencySlider = QtWidgets.QSlider(self.centralWidget)
        self.transparencySlider.setOrientation(QtCore.Qt.Horizontal)
        self.transparencySlider.setObjectName("transparencySlider")
        self.verticalLayout_3.addWidget(self.transparencySlider)
        self.gridLayout.addLayout(self.verticalLayout_3, 3, 1, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Options"))
        self.stackRadioButton.setText(_translate("MainWindow", "Stack"))
        self.listRadioButton.setText(_translate("MainWindow", "List"))
        self.concatRadioButton.setText(_translate("MainWindow", "Concat"))
        self.randomRadioButton.setText(_translate("MainWindow", "Random LOL"))
        self.label.setText(_translate("MainWindow", "Total Elements"))
        self.label_3.setText(_translate("MainWindow", "Total Bytes Elements"))
        self.label_5.setText(_translate("MainWindow", "Transparency"))
        self.label_6.setText(_translate("MainWindow", "Value"))

